# Source Generated with Decompyle++
# File: home_table.pyc (Python 3.8)

CHIP_MODE_297L = 0
CHIP_MODE_FS01 = 1
CHIP_MODE_FS32 = 2
CHIP_MODE_BLE = 3
PN297_CHIP_MODE_NAME = 'XN297L'
FS01_CHIP_MODE_NAME = 'FS01'
FS32_CHIP_MODE_NAME = 'FS32'
BLE_CHIP_MODE_NAME = 'Bluetooth-LE Beacon'
chip_mode_list_simple = [
    PN297_CHIP_MODE_NAME,
    BLE_CHIP_MODE_NAME]
chip_mode_list = [
    PN297_CHIP_MODE_NAME,
    FS01_CHIP_MODE_NAME,
    FS32_CHIP_MODE_NAME,
    BLE_CHIP_MODE_NAME]
STATE_211_MODE = True
def_form_config = {
    'endian': 1,
    'chipMode': 0,
    'channel': 2478,
    'dataRate': 0,
    'workMode': 0,
    'txPower': 9,
    'xtalFreq': 1,
    'crc': 0,
    'enDPL': 0,
    'enWhite': 0,
    'whiteInit': '7F',
    'enTxNoAck': 1,
    'crcSkipAddr': 0,
    'scrSkipAddr': 0,
    'txLen': 32,
    'rxLen': 32,
    'tRxDelayTimeUs': 500,
    'rxTimeoutUs': 7000,
    'autoDelayUs': 0,
    'autoMaxCnt': 3,
    'txAddrWidth': 5,
    'headNum': 1,
    'rxAddrWidth': 5,
    'enMultiPipe': 0,
    'enManuPid': 0,
    'enRxPlLenLimit': 0,
    'bleHeadNum': 2,
    'bleHead0': '42',
    'bleHead1': '00',
    's2S8Mode': 0,
    'lengthFilterMode': 0,
    'whiteListOffset': 0,
    'whiteListMatchMode': 0,
    'bleChannel': 0,
    'whiteListLen': 0,
    'spiClk': 0,
    'rxMode': 2,
    'txMode': 0,
    'interruptMask': 255,
    'custome': False }
table_config_list_simple = [
    {
        'name': 'Standard XN297L Normal Tx',
        'chipMode': 0,
        'trxMode': 1,
        'txMode': 0,
        'rxMode': 2,
        'workMode': 0,
        'dataRate': 0,
        'channel': 2478,
        'txAddrWidth': 5,
        'txPower': 9,
        'crc': 2,
        'txLen': 32,
        'rxLen': 32,
        'enWhite': 1,
        'enDPL': 0,
        'enMultiPipe': 0,
        'txAddress': 'CCCCCCCCCC',
        'rxAddress': 'CCCCCCCCCC',
        'description': 'This project configures the radio as the standard XN297L Normal packet. When the Project is loaded to the PAN211 EVB, the yellow LED toggles once after a packet is transmitted. \n<br />Note: This project works with the "standard XN297L Normal Rx" project.\n\n      ' },
    {
        'name': 'Standard XN297L Normal Rx',
        'chipMode': 0,
        'trxMode': 0,
        'txMode': 0,
        'rxMode': 2,
        'workMode': 0,
        'dataRate': 0,
        'channel': 2478,
        'txPower': 9,
        'crc': 2,
        'txLen': 32,
        'rxLen': 32,
        'enWhite': 1,
        'enDPL': 0,
        'enMultiPipe': 0,
        'txAddress': 'CCCCCCCCCC',
        'rxAddress': 'CCCCCCCCCC',
        'description': 'This project configures the radio as the standard XN297L Normal packet. When the Project is loaded to the PAN211 EVB, the green LED toggles once after a packet is received. \n<br />Note: This project works with the "standard XN297L Normal Tx" project.\n          ' },
    {
        'name': 'Custom XN297L Normal Tx & Rx',
        'chipMode': 0,
        'trxMode': 0,
        'txMode': 0,
        'rxMode': 2,
        'workMode': 0,
        'dataRate': 0,
        'channel': 2478,
        'txPower': 9,
        'crc': 2,
        'txLen': 32,
        'rxLen': 32,
        'enWhite': 1,
        'enDPL': 0,
        'enMultiPipe': 0,
        'txAddress': 'CCCCCCCCCC',
        'rxAddress': 'CCCCCCCCCC',
        'custome': True,
        'description': 'This project configures the radio with the selected radio parameters. It is the user\'s responsibility to set the appropriate parameters by refering to the SDK examples such as:  <br /><a href="https://docs.panchip.com/pan211xdk-doc/03_example/00_normal_tx_readme.html">normal_tx</a>, \n    <a href="https://docs.panchip.com/pan211xdk-doc/03_example/01_normal_tx_reuse_readme.html">normal_tx_reuse</a>, <a href="https://docs.panchip.com/pan211xdk-doc/03_example/02_normal_rx_readme.html">normal_rx</a>, <a href="https://docs.panchip.com/pan211xdk-doc/03_example/03_normal_rx_single_readme.html">normal_rx_single</a>,\n     <a href="https://docs.panchip.com/pan211xdk-doc/03_example/04_normal_rx_timeout_readme.html">normal_rx_timeout</a>, <a href="https://docs.panchip.com/pan211xdk-doc/03_example/08_pingpong_readme.html">pingpong</a>, <a href="https://docs.panchip.com/pan211xdk-doc/03_example/13_multipipe_readme.html">multipipe</a>\n          ' },
    {
        'name': 'Standard XN297L Enhance Tx',
        'chipMode': 0,
        'trxMode': 1,
        'txMode': 0,
        'rxMode': 0,
        'workMode': 1,
        'dataRate': 0,
        'channel': 2478,
        'txPower': 9,
        'crc': 2,
        'txLen': 32,
        'rxLen': 32,
        'enWhite': 1,
        'enDPL': 1,
        'autoMaxCnt': 3,
        'autoDelayUs': 250,
        'enTxNoAck': 0,
        'enMultiPipe': 0,
        'txAddress': 'CCCCCCCCCC',
        'rxAddress': 'CCCCCCCCCC',
        'description': 'This project configures the radio as the standard XN297L Enhance packet. When the Project is loaded to the PAN211 EVB, the yellow LED toggles  once after a packet is transmitted  and yellow LED toggles after a ACK packet is received.\n<br />Note: This project works with the "standard XN297L Enhance Rx" project.\n      ' },
    {
        'name': 'Standard XN297L Enhance Rx',
        'chipMode': 0,
        'trxMode': 0,
        'txMode': 0,
        'rxMode': 0,
        'workMode': 1,
        'dataRate': 0,
        'channel': 2478,
        'txPower': 9,
        'crc': 2,
        'txLen': 32,
        'rxLen': 32,
        'enWhite': 1,
        'enDPL': 1,
        'autoMaxCnt': 3,
        'autoDelayUs': 250,
        'trxDelayTimeUs': 0,
        'enTxNoAck': 0,
        'enMultiPipe': 0,
        'txAddress': 'CCCCCCCCCC',
        'rxAddress': 'CCCCCCCCCC',
        'description': 'This project configures the radio as the standard XN297L Enhance packet. When the Project is loaded to the PAN211 EVB, the green LED toggles after a valid packet is received and the green LED toggles after a ACK packet is transmitted.\n<br />Note: This project works with the "standard XN297L Enhance Tx" project.\n          ' },
    {
        'name': 'Custom XN297L Enhance Tx / Rx',
        'chipMode': 0,
        'trxMode': 0,
        'txMode': 0,
        'rxMode': 0,
        'workMode': 1,
        'dataRate': 0,
        'channel': 2478,
        'txPower': 9,
        'crc': 2,
        'txLen': 32,
        'rxLen': 32,
        'enWhite': 1,
        'enDPL': 1,
        'autoMaxCnt': 3,
        'autoDelayUs': 250,
        'trxDelayTimeUs': 500,
        'enTxNoAck': 0,
        'enMultiPipe': 0,
        'txAddress': 'CCCCCCCCCC',
        'rxAddress': 'CCCCCCCCCC',
        'custome': True,
        'description': 'This project configures the radio as the custom XN297L Enhance packet. It is the user\'s responsibility to set the appropriate parameters by refering to the SDK examples such as: <br /><a href="https://docs.panchip.com/pan211xdk-doc/03_example/05_enhance_tx_readme.html">enhance_tx</a>, <a href="https://docs.panchip.com/pan211xdk-doc/03_example/06_enhance_rx_readme.html">enhance_rx</a>, <a href="https://docs.panchip.com/pan211xdk-doc/03_example/07_enhance_rx_timeout_readme.html">enhance_rx_timeout</a>, <a href="https://docs.panchip.com/pan211xdk-doc/03_example/13_multipipe_readme.html">multipipe</a>.\n          ' },
    {
        'name': 'Standard Bluetooth-LE Beacon Tx',
        'chipMode': 3,
        'trxMode': 1,
        'workMode': 0,
        'dataRate': 0,
        'channel': 2478,
        'txPower': 9,
        'endian': 0,
        'crc': 3,
        'txLen': 19,
        'rxLen': 19,
        'enWhite': 1,
        'enDPL': 0,
        'lengthFilterMode': 1,
        'whiteListMatchMode': 0,
        'whiteList': 'CCCCCCCCCCCC',
        'enMultiPipe': 0,
        'description': 'This project configures the radio as the standard Bluetooth-LE Beacon packet. If the Project is loaded to the PAN211 EVB, the yellow LED toggles once after a packet is transmitted.\n<br />Note: This project works with the "standard Bluetooth-LE Beacon Rx" project.\n\n      ' },
    {
        'name': 'Standard Bluetooth-LE Beacon Rx',
        'chipMode': 3,
        'trxMode': 0,
        'workMode': 0,
        'dataRate': 0,
        'channel': 2478,
        'txPower': 9,
        'endian': 0,
        'crc': 3,
        'txLen': 19,
        'rxLen': 19,
        'enWhite': 1,
        'enDPL': 0,
        'lengthFilterMode': 1,
        'whiteListMatchMode': 0,
        'whiteList': 'CCCCCCCCCCCC',
        'enMultiPipe': 0,
        'description': 'This project configures the radio as the standard Bluetooth-LE Beacon packet. If the Project is loaded to the PAN211 EVB, the green LED toggles once after a packet is received. \n<br />Note: This project works with the "standard Bluetooth-LE Beacon Tx" project.\n\n      ' },
    {
        'name': 'Custom Bluetooth-LE Tx & Rx',
        'chipMode': 3,
        'trxMode': 0,
        'workMode': 0,
        'dataRate': 0,
        'channel': 2478,
        'txPower': 9,
        'endian': 0,
        'crc': 3,
        'txLen': 19,
        'rxLen': 19,
        'enWhite': 1,
        'lengthFilterMode': 1,
        'whiteListMatchMode': 0,
        'whiteList': 'CCCCCCCCCCCC',
        'enMultiPipe': 0,
        'custome': True,
        'description': 'This project configures the radio as the custom Bluetooth-LE packet. It is the user\'s responsibility to set the appropriate parameters by refering to the SDK examples such as: <br /> <a href="https://docs.panchip.com/pan211xdk-doc/03_example/10_ble_tx_readme.html">ble_tx</a>, <a href="https://docs.panchip.com/pan211xdk-doc/03_example/11_ble_rx_readme.html">ble_rx</a>, \n<a href="https://docs.panchip.com/pan211xdk-doc/03_example/17_longrange_ble_tx_readme.html">longrange_ble_tx</a>, <a href="https://docs.panchip.com/pan211xdk-doc/03_example/18_longrange_ble_rx_readme.html">longrange_ble_rx</a>\n      ' },
    {
        'name': 'Standard LongRange Tx',
        'chipMode': 3,
        'trxMode': 1,
        'workMode': 0,
        'dataRate': 0,
        'channel': 2478,
        'txPower': 9,
        'endian': 0,
        'crc': 3,
        'txLen': 32,
        'rxLen': 32,
        'enWhite': 1,
        'headNum': 0,
        'txAddrWidth': 4,
        'bleHead0': '0',
        'bleHead1': '0',
        's2S8Mode': 2,
        'enDPL': 0,
        'lengthFilterMode': 1,
        'whiteListMatchMode': 0,
        'whiteList': 'CCCCCCCCCCCC',
        'enMultiPipe': 0,
        'description': 'This project configures the radio as the standard LongRange packet. If the Project is loaded to the PAN211 EVB, the yellow LED toggles once after a packet is transmitted.\n<br />Note: This project works with the "standard Bluetooth-LE Beacon Rx" project.\n      ' },
    {
        'name': 'Standard LongRange Rx',
        'chipMode': 3,
        'trxMode': 0,
        'workMode': 0,
        'dataRate': 0,
        'channel': 2478,
        'txPower': 9,
        'endian': 0,
        'crc': 3,
        'txLen': 32,
        'rxLen': 32,
        'enWhite': 1,
        'txAddrWidth': 4,
        'bleHead0': '0',
        'bleHead1': '0',
        'headNum': 0,
        's2S8Mode': 2,
        'enDPL': 0,
        'lengthFilterMode': 1,
        'whiteListMatchMode': 0,
        'whiteList': 'CCCCCCCCCCCC',
        'enMultiPipe': 0,
        'description': 'This project configures the radio as the standard Bluetooth-LE Beacon packet. If the Project is loaded to the PAN211 EVB, the green LED toggles once after a packet is received. \n<br />Note: This project works with the "standard Bluetooth-LE Beacon Tx" project.\n      ' },
    {
        'name': 'Carrier Wave Test',
        'chipMode': 0,
        'trxMode': 2,
        'txMode': 1,
        'rxMode': 2,
        'workMode': 0,
        'dataRate': 0,
        'channel': 2478,
        'txPower': 9,
        'crc': 2,
        'txLen': 32,
        'rxLen': 32,
        'enWhite': 1,
        'enDPL': 0,
        'enMultiPipe': 0,
        'txAddress': 'CCCCCCCCCC',
        'rxAddress': 'CCCCCCCCCC',
        'description': 'This project configures the radio as the Carrier Wave packet.\n        \n      ' }]
scroll_style = '\n       QScrollBar:horizontal {\n    height: 10px;\n    background: #F1F1F1;\n}\nQScrollBar::handle:horizontal {\n    background: #CCCCCC;\n    min-width: 20px;\n    border-radius: 5px;\n}\nQScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n    background: none;\n    border: none;\n    height: 0px;\n}\nQScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n    background: none;\n}\nQScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n    border: 2px solid grey;\n    width: 3px;\n    height: 3px;\n    background: white;\n}\nQScrollBar::add-page:horizontal:hover, QScrollBar::sub-page:horizontal:hover {\n    background: #EEEEEE;\n}\n        '
